{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "mysql-helm-chart.fullname" . }}
  namespace:  {{ include "mysql-helm-chart.namespace" . }}
  labels: {{- include "mysql-helm-chart.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistence.className }}
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}